# Generated by Django 6.0.6 on 2026-06-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.CharField(help_text='e.g., PayID, BSB/Account Number, or Transaction Reference identifier', max_length=100, unique=True)),
                ('pay_name', models.CharField(help_text='The official registered legal name associated with the payment channel', max_length=255)),
                ('pay_qr', models.ImageField(blank=True, null=True, upload_to='payment_channels/qr_codes/')),
                ('qr_description', models.TextField(blank=True, help_text='Instructions or terms displayed to the user beneath the QR code layout', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Detail Specification',
                'verbose_name_plural': 'Payment Details Specifications',
                'db_table': 'payment_details',
            },
        ),
        migrations.CreateModel(
            name='AssignmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ss', models.ImageField(help_text='The verification receipt/screenshot uploaded by the student client', upload_to='assignments/payment_receipts/')),
                ('pay_amount', models.DecimalField(decimal_places=2, help_text='The exact monetary amount processed for this transaction milestone', max_digits=10)),
                ('pay_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='assignment.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignment_payments',
                'ordering': ['-pay_at'],
            },
        ),
    ]
