# Generated by Django 6.0.6 on 2026-06-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_date', models.DateTimeField(auto_now_add=True)),
                ('provided_is_active', models.BooleanField(default=True)),
                ('provided_status', models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_receipt_date', models.DateTimeField(blank=True, null=True)),
                ('payment_done_date', models.DateTimeField(blank=True, null=True)),
                ('payment_is_active', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/screenshots/')),
                ('payment_details_image', models.ImageField(blank=True, null=True, upload_to='payments/details/')),
                ('doing_date', models.DateTimeField(blank=True, null=True)),
                ('doing_is_active', models.BooleanField(default=False)),
                ('doing_status', models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('completed_is_active', models.BooleanField(default=False)),
                ('completed_status', models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='assignment.assignment')),
            ],
            options={
                'verbose_name': 'Assignment Progress',
                'verbose_name_plural': 'Assignment Progresses',
                'db_table': 'assignment_progress',
            },
        ),
    ]
