# Generated by Django 6.0.6 on 2026-06-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentprogress', '0002_assignmentprogress_payment_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentprogress',
            name='provided_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('doing', 'Doing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
