"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
import environ  # Import django-environ by Thapa


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environ by Thapa
env = environ.Env(
    # set casting and default values
    DEBUG=(bool, False)
)

# Read .env file (overwrite=True so mounted .env wins over stale Docker env vars)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'), overwrite=True)




SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')


# Application definition

INSTALLED_APPS = [
    'user',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',

    'banner',
    'social',
    'busydate',
    'assignment',
    'assignmentprogress',
    'notification',
    'payment',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database configuration (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Australia/Sydney'

USE_I18N = True

USE_TZ = True




AUTH_USER_MODEL = 'user.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  
        'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    }






# ==============================================================================
# STATIC & USER UPLOADED MEDIA STORAGE CONFIGURATION (DigitalOcean Spaces Integration)
# ==============================================================================

# 1. Collected Static Files (Always served locally via WhiteNoise inside Docker)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 2. DigitalOcean Spaces Toggle Switch Engine
# Checks for DO keys inside your mounted .env file to dynamically route media storage
USE_SPACES = env.bool('USE_SPACES', default=bool(env('DO_SPACES_KEY', default='') and env('DO_SPACES_SECRET', default='')))

if USE_SPACES:
    # Authenticated credentials parsed directly out of your .env file
    AWS_ACCESS_KEY_ID = env('DO_SPACES_KEY')
    AWS_SECRET_ACCESS_KEY = env('DO_SPACES_SECRET')
    AWS_STORAGE_BUCKET_NAME = env('DO_SPACES_BUCKET', default='level-esport-matchmaking-bucket')
    
    # Regional and endpoint mapping coordinates
    AWS_S3_REGION_NAME = env('DO_SPACES_REGION', default='blr1')
    AWS_S3_ENDPOINT_URL = f"https://{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.cdn.digitaloceanspaces.com"
    
    # CRITICAL: Keep files separated from your previous project using a clean subfolder prefix!
    AWS_LOCATION = 'doit-prod'

    # Objects are private by default on DO Spaces; allow direct CDN/browser access.
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False

    # Modernized Django Unified Storage Engine Backend Routing (Django 4.2+)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage", # Handled via Nginx/Docker
        },
    }
    
    # Target absolute absolute URI root path configuration
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"

else:
    # Minimal Local Fallback Storage Engine (Ideal for local testing/development)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'




# Firebase Admin SDK (credentials loaded from .env)
FIREBASE_PROJECT_ID = env('FIREBASE_PROJECT_ID')
FIREBASE_CLIENT_EMAIL = env('FIREBASE_CLIENT_EMAIL')
FIREBASE_PRIVATE_KEY_ID = env('FIREBASE_PRIVATE_KEY_ID')
FIREBASE_PRIVATE_KEY = env('FIREBASE_PRIVATE_KEY')
FIREBASE_CLIENT_ID = env('FIREBASE_CLIENT_ID')
FIREBASE_CLIENT_X509_CERT_URL = env('FIREBASE_CLIENT_X509_CERT_URL')
FIREBASE_ENABLE_TEST_BROADCAST = env.bool('FIREBASE_ENABLE_TEST_BROADCAST')
FIREBASE_TEST_TOPIC = env('FIREBASE_TEST_TOPIC')
FIREBASE_TEST_BANNER_URL = env('FIREBASE_TEST_BANNER_URL')

