# Generated by Django 6.0.6 on 2026-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(choices=[('heavy_assignments', 'Heavy Assignments'), ('holiday', 'Holiday')], default='heavy_assignments', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'busy_dates',
                'ordering': ['date'],
            },
        ),
    ]
