# Generated by Django 6.0.6 on 2026-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='social_name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'Whatsapp'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('tiktok', 'Tiktok')], max_length=255),
        ),
    ]
