# Generated by Django 6.0.6 on 2026-06-12 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('assessment', 'Assessment'), ('tutorial', 'Tutorial'), ('others', 'Others')], default='assessment', max_length=50)),
                ('work_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('doing', 'Doing'), ('completed', 'Completed')], default='in_review', max_length=30)),
                ('is_paid', models.BooleanField(default=False)),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-provided_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assignments/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignment.assignment')),
            ],
            options={
                'db_table': 'assignment_files',
            },
        ),
    ]
