# Generated by Django 6.0.6 on 2026-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completed_file',
            field=models.FileField(blank=True, help_text='The final completed solution file uploaded by the assignment helper', null=True, upload_to='assignments/completed_solutions/'),
        ),
    ]
