# Generated by Django 6.0.6 on 2026-06-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_completed_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('doing', 'Doing'), ('completed', 'Completed'), ('unsubmitted', 'Unsubmitted')], default='in_review', max_length=30),
        ),
    ]
