# Generated by Django 6.0.6 on 2026-06-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('doing', 'Doing'), ('completed', 'Completed'), ('unsubmitted', 'Unsubmitted')], default='pending', max_length=30),
        ),
    ]
