# Generated by Django 6.0.6 on 2026-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_add_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='changes_request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='changes_request_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('doing', 'Doing'), ('completed', 'Completed'), ('unsubmitted', 'Unsubmitted')], default='in_review', max_length=30),
        ),
    ]
