# Generated by Django 6.0.6 on 2026-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignment_changes_request_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='changes_request_resolved_count',
            field=models.IntegerField(default=0),
        ),
    ]
