# Generated by Django 6.0.6 on 2026-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_added_by_assignment_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
