# Generated by Django 6.0.6 on 2026-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_assignment_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending'), ('payment_rejected', 'Payment Rejected'), ('doing', 'Doing'), ('completed', 'Completed'), ('unsubmitted', 'Unsubmitted')], default='pending', max_length=30),
        ),
    ]
